import { describe, expect, expectTypeOf, it } from "vitest";

import {
  auditEventsTable,
  bigTasksTable,
  candidateTaskContractBindingsTable,
  chatThreadsTable,
  contextDigestsTable,
  contextItemsTable,
  ExecutionInputPreflight,
  ExecutionInputPreflightError,
  executionRunsTable,
  orchestrationMaterializationsTable,
  orchestrationPlanCandidatesTable,
  orchestrationPlanningTracksTable,
  orchestrationReviewDecisionsTable,
  openTaskDatabase,
  OperationalJitContextAssembler,
  OperationalJitContextAssemblyError,
  projectsTable,
  STORAGE_ERROR_CODES,
  subtaskImplementationCheckpointsTable,
  subtasksTable,
  taskContractsTable,
  taskDependenciesTable,
  TASK_CONTRACT_AUTHORITY_READINESS,
  TaskStorage,
  TaskStorageError,
  TrustedRepositorySourceError,
  TrustedRepositorySourceReader,
} from "@codex-task-console/storage";
import type {
  ApprovedTaskContractAuthority,
  ActiveContextItemBucket,
  ActiveContextItemSnapshot,
  AllowedRawContextItemBucket,
  AllowedRawContextItemSnapshot,
  BoundedDurableExecutionHistory,
  BoundedDurableExecutionHistoryOptions,
  BoundedDurableExecutionHistoryThread,
  BindChatThreadProviderReferenceInput,
  CreateChatThreadInput,
  CreateExecutionRunInput,
  ExecutionInputPreflightErrorCode,
  ExecutionInputPreflightResult,
  FinishExecutionRunInput,
  DurableOrchestrationPlanningSnapshot,
  DurablePlanningReviewBundle,
  DurablePlanCandidateArtifact,
  DurableReviewDecisionArtifact,
  JitContextStorageSourceSnapshot,
  OperationalJitContextAssemblyErrorCode,
  OperationalJitContextProfile,
  StartExecutionRunInput,
  TaskContractAuthorityReadiness,
  TrustedRepositorySourceErrorCode,
  TrustedRepositorySourceSnapshot,
  TrustedRepositorySourceTextBlock,
} from "@codex-task-console/storage";

describe("storage package public exports", () => {
  it("exposes only the deliberate storage contract surface", () => {
    expect(openTaskDatabase).toBeTypeOf("function");
    expect(TaskStorage).toBeTypeOf("function");
    expect(TaskStorageError).toBeTypeOf("function");
    expect(OperationalJitContextAssembler).toBeTypeOf("function");
    expect(OperationalJitContextAssemblyError).toBeTypeOf("function");
    expect(ExecutionInputPreflight).toBeTypeOf("function");
    expect(ExecutionInputPreflightError).toBeTypeOf("function");
    expect(TrustedRepositorySourceReader).toBeTypeOf("function");
    expect(TrustedRepositorySourceError).toBeTypeOf("function");
    expect(STORAGE_ERROR_CODES).toContain("MIGRATION_FAILED");
    expect(projectsTable).toBeDefined();
    expect(bigTasksTable).toBeDefined();
    expect(candidateTaskContractBindingsTable).toBeDefined();
    expect(chatThreadsTable).toBeDefined();
    expect(executionRunsTable).toBeDefined();
    expect(orchestrationMaterializationsTable).toBeDefined();
    expect(orchestrationPlanCandidatesTable).toBeDefined();
    expect(orchestrationPlanningTracksTable).toBeDefined();
    expect(orchestrationReviewDecisionsTable).toBeDefined();
    expect(contextDigestsTable).toBeDefined();
    expect(auditEventsTable).toBeDefined();
    expect(contextItemsTable).toBeDefined();
    expect(subtasksTable).toBeDefined();
    expect(taskContractsTable).toBeDefined();
    expect(taskDependenciesTable).toBeDefined();
    expect(subtaskImplementationCheckpointsTable).toBeDefined();
    expect(TASK_CONTRACT_AUTHORITY_READINESS).toEqual([
      "TASK_CONTRACT_AUTHORITY_READY",
      "TASK_CONTRACT_AUTHORITY_NOT_READY",
    ]);
    expectTypeOf<ApprovedTaskContractAuthority>().toBeObject();
    expectTypeOf<ActiveContextItemBucket>().toBeObject();
    expectTypeOf<ActiveContextItemSnapshot>().toBeObject();
    expectTypeOf<AllowedRawContextItemBucket>().toBeObject();
    expectTypeOf<AllowedRawContextItemSnapshot>().toBeObject();
    expectTypeOf<BoundedDurableExecutionHistory>().toBeObject();
    expectTypeOf<BoundedDurableExecutionHistoryOptions>().toBeObject();
    expectTypeOf<BoundedDurableExecutionHistoryThread>().toBeObject();
    expectTypeOf<BindChatThreadProviderReferenceInput>().toBeObject();
    expectTypeOf<CreateChatThreadInput>().toBeObject();
    expectTypeOf<CreateExecutionRunInput>().toBeObject();
    expectTypeOf<StartExecutionRunInput>().toBeObject();
    expectTypeOf<FinishExecutionRunInput>().toBeObject();
    expectTypeOf<DurableOrchestrationPlanningSnapshot>().toBeObject();
    expectTypeOf<DurablePlanningReviewBundle>().toBeObject();
    expectTypeOf<DurablePlanCandidateArtifact>().toBeObject();
    expectTypeOf<DurableReviewDecisionArtifact>().toBeObject();
    expectTypeOf<JitContextStorageSourceSnapshot>().toBeObject();
    expectTypeOf<OperationalJitContextAssemblyErrorCode>().toBeString();
    expectTypeOf<OperationalJitContextProfile>().toBeString();
    expectTypeOf<ExecutionInputPreflightErrorCode>().toBeString();
    expectTypeOf<ExecutionInputPreflightResult>().toBeObject();
    expectTypeOf<TrustedRepositorySourceSnapshot>().toBeObject();
    expectTypeOf<TrustedRepositorySourceTextBlock>().toBeObject();
    expectTypeOf<TrustedRepositorySourceErrorCode>().toBeString();
    expectTypeOf<TaskContractAuthorityReadiness>().toBeString();
  });
});
