import { describe, expect, expectTypeOf, it } from "vitest";

import {
  auditEventsTable,
  bigTasksTable,
  candidateTaskContractBindingsTable,
  chatThreadsTable,
  contextDigestsTable,
  contextItemsTable,
  DURABLE_WORKFLOW_EVIDENCE_KINDS,
  DURABLE_WORKFLOW_EVIDENCE_PRODUCERS,
  durableWorkflowEvidenceTable,
  durableWorkflowHumanRequirementsTable,
  durableWorkflowTransitionsTable,
  ExecutionInputPreflight,
  ExecutionInputPreflightError,
  executionRunsTable,
  orchestrationMaterializationsTable,
  orchestrationPlanCandidatesTable,
  orchestrationPlanningTracksTable,
  orchestrationReviewDecisionsTable,
  openTaskDatabase,
  OperationalJitContextAssembler,
  OperationalJitContextAssemblyError,
  projectsTable,
  STORAGE_ERROR_CODES,
  subtaskImplementationCheckpointsTable,
  subtaskWorkflowInstancesTable,
  subtasksTable,
  taskContractsTable,
  taskDependenciesTable,
  TASK_CONTRACT_AUTHORITY_READINESS,
  TaskStorage,
  TaskStorageError,
  TrustedRepositorySourceError,
  TrustedRepositorySourceReader,
  workflowInitializationReceiptsTable,
} from "@codex-task-console/storage";
import type {
  ApprovedTaskContractAuthority,
  ActiveContextItemBucket,
  ActiveContextItemSnapshot,
  AcceptDurableWorkflowEvidenceInput,
  AdvanceDurableWorkflowInput,
  AdvanceDurableWorkflowResult,
  AllowedRawContextItemBucket,
  AllowedRawContextItemSnapshot,
  BoundedDurableExecutionHistory,
  BoundedDurableExecutionHistoryOptions,
  BoundedDurableExecutionHistoryThread,
  BindChatThreadProviderReferenceInput,
  CreateChatThreadInput,
  CreateExecutionRunInput,
  ExecutionInputPreflightErrorCode,
  ExecutionInputPreflightResult,
  FinishExecutionRunInput,
  DurableOrchestrationPlanningSnapshot,
  DurablePlanningReviewBundle,
  DurablePlanCandidateArtifact,
  DurableReviewDecisionArtifact,
  DurableSubtaskWorkflowInitialization,
  DurableSubtaskWorkflowInstance,
  DurableWorkflowControlView,
  DurableWorkflowEvidence,
  DurableWorkflowEvidenceKind,
  DurableWorkflowEvidenceOutcome,
  DurableWorkflowEvidenceProducer,
  DurableWorkflowEvidenceReference,
  DurableWorkflowHumanRequirement,
  DurableWorkflowTransition,
  DurableWorkflowTransitionEvidenceReference,
  JitContextStorageSourceSnapshot,
  OperationalJitContextAssemblyErrorCode,
  OperationalJitContextProfile,
  RequestDurableMaterializedGraphChangeInput,
  RequestDurableMaterializedGraphChangeResult,
  StartExecutionRunInput,
  TaskContractAuthorityReadiness,
  TrustedRepositorySourceErrorCode,
  TrustedRepositorySourceSnapshot,
  TrustedRepositorySourceTextBlock,
} from "@codex-task-console/storage";

describe("storage package public exports", () => {
  it("exposes only the deliberate storage contract surface", () => {
    expect(openTaskDatabase).toBeTypeOf("function");
    expect(TaskStorage).toBeTypeOf("function");
    expect(TaskStorageError).toBeTypeOf("function");
    expect(OperationalJitContextAssembler).toBeTypeOf("function");
    expect(OperationalJitContextAssemblyError).toBeTypeOf("function");
    expect(ExecutionInputPreflight).toBeTypeOf("function");
    expect(ExecutionInputPreflightError).toBeTypeOf("function");
    expect(TrustedRepositorySourceReader).toBeTypeOf("function");
    expect(TrustedRepositorySourceError).toBeTypeOf("function");
    expect(STORAGE_ERROR_CODES).toContain("MIGRATION_FAILED");
    expect(projectsTable).toBeDefined();
    expect(bigTasksTable).toBeDefined();
    expect(candidateTaskContractBindingsTable).toBeDefined();
    expect(chatThreadsTable).toBeDefined();
    expect(executionRunsTable).toBeDefined();
    expect(orchestrationMaterializationsTable).toBeDefined();
    expect(orchestrationPlanCandidatesTable).toBeDefined();
    expect(orchestrationPlanningTracksTable).toBeDefined();
    expect(orchestrationReviewDecisionsTable).toBeDefined();
    expect(contextDigestsTable).toBeDefined();
    expect(auditEventsTable).toBeDefined();
    expect(contextItemsTable).toBeDefined();
    expect(durableWorkflowEvidenceTable).toBeDefined();
    expect(durableWorkflowTransitionsTable).toBeDefined();
    expect(durableWorkflowHumanRequirementsTable).toBeDefined();
    expect(subtasksTable).toBeDefined();
    expect(taskContractsTable).toBeDefined();
    expect(taskDependenciesTable).toBeDefined();
    expect(subtaskImplementationCheckpointsTable).toBeDefined();
    expect(subtaskWorkflowInstancesTable).toBeDefined();
    expect(workflowInitializationReceiptsTable).toBeDefined();
    expect(TASK_CONTRACT_AUTHORITY_READINESS).toEqual([
      "TASK_CONTRACT_AUTHORITY_READY",
      "TASK_CONTRACT_AUTHORITY_NOT_READY",
    ]);
    expect(DURABLE_WORKFLOW_EVIDENCE_KINDS).toContain(
      "FRESH_QA_OUTCOME_RECORDED",
    );
    expect(DURABLE_WORKFLOW_EVIDENCE_PRODUCERS).toEqual([
      "OPERATIONAL_GATE",
      "WORKFLOW_ROLE",
      "HUMAN_AUTHORITY",
      "DELIVERY_CONTROL",
    ]);
    expectTypeOf<AcceptDurableWorkflowEvidenceInput>().toBeObject();
    expectTypeOf<AdvanceDurableWorkflowInput>().toBeObject();
    expectTypeOf<AdvanceDurableWorkflowResult>().toBeObject();
    expectTypeOf<ApprovedTaskContractAuthority>().toBeObject();
    expectTypeOf<ActiveContextItemBucket>().toBeObject();
    expectTypeOf<ActiveContextItemSnapshot>().toBeObject();
    expectTypeOf<AllowedRawContextItemBucket>().toBeObject();
    expectTypeOf<AllowedRawContextItemSnapshot>().toBeObject();
    expectTypeOf<BoundedDurableExecutionHistory>().toBeObject();
    expectTypeOf<BoundedDurableExecutionHistoryOptions>().toBeObject();
    expectTypeOf<BoundedDurableExecutionHistoryThread>().toBeObject();
    expectTypeOf<BindChatThreadProviderReferenceInput>().toBeObject();
    expectTypeOf<CreateChatThreadInput>().toBeObject();
    expectTypeOf<CreateExecutionRunInput>().toBeObject();
    expectTypeOf<StartExecutionRunInput>().toBeObject();
    expectTypeOf<FinishExecutionRunInput>().toBeObject();
    expectTypeOf<DurableOrchestrationPlanningSnapshot>().toBeObject();
    expectTypeOf<DurablePlanningReviewBundle>().toBeObject();
    expectTypeOf<DurablePlanCandidateArtifact>().toBeObject();
    expectTypeOf<DurableReviewDecisionArtifact>().toBeObject();
    expectTypeOf<DurableSubtaskWorkflowInitialization>().toBeObject();
    expectTypeOf<DurableSubtaskWorkflowInstance>().toBeObject();
    expectTypeOf<DurableWorkflowControlView>().toBeObject();
    expectTypeOf<DurableWorkflowEvidence>().toBeObject();
    expectTypeOf<DurableWorkflowEvidenceKind>().toBeString();
    expectTypeOf<DurableWorkflowEvidenceOutcome>().toBeString();
    expectTypeOf<DurableWorkflowEvidenceProducer>().toBeString();
    expectTypeOf<DurableWorkflowEvidenceReference>().toBeObject();
    expectTypeOf<DurableWorkflowHumanRequirement>().toBeObject();
    expectTypeOf<DurableWorkflowTransition>().toBeObject();
    expectTypeOf<DurableWorkflowTransitionEvidenceReference>().toBeObject();
    expectTypeOf<JitContextStorageSourceSnapshot>().toBeObject();
    expectTypeOf<OperationalJitContextAssemblyErrorCode>().toBeString();
    expectTypeOf<OperationalJitContextProfile>().toBeString();
    expectTypeOf<RequestDurableMaterializedGraphChangeInput>().toBeObject();
    expectTypeOf<RequestDurableMaterializedGraphChangeResult>().toBeObject();
    expectTypeOf<ExecutionInputPreflightErrorCode>().toBeString();
    expectTypeOf<ExecutionInputPreflightResult>().toBeObject();
    expectTypeOf<TrustedRepositorySourceSnapshot>().toBeObject();
    expectTypeOf<TrustedRepositorySourceTextBlock>().toBeObject();
    expectTypeOf<TrustedRepositorySourceErrorCode>().toBeString();
    expectTypeOf<TaskContractAuthorityReadiness>().toBeString();
  });
});
