import { describe, expect, it } from "vitest";

import * as domainExports from "../src/index.js";

import {
  AcceptedPromotedContextSnapshotDataSchema,
  AuditEventSchema,
  BudgetPolicySchema,
  BoundedRetestTargetSchema,
  ChatThreadSchema,
  ContextDigestSchema,
  DeterministicEngineeringFactDataSchema,
  ContextItemSchema,
  ContextScopeSchema,
  DependencyRequiredGateSchema,
  DurableTaskSchema,
  ExecutionProviderDescriptorSchema,
  ExecutionRunSchema,
  JitContextPacketCompilationInputSchema,
  JitContextPacketCompilationReasonSchema,
  JitContextPacketProfileKindSchema,
  JitContextPacketSchema,
  NativeSubagentOwnershipSchema,
  NormalizedUsageSchema,
  ProviderRunReferenceSchema,
  ProviderThreadReferenceSchema,
  PromotedContextAcceptanceEvaluationSchema,
  PromotedContextAcceptanceReasonSchema,
  PromotedContextAcceptanceRequirementSchema,
  PromotedContextHumanConfirmationEvaluationSchema,
  PromotedContextHumanConfirmationEvidenceSchema,
  PromotedContextHumanConfirmationReasonSchema,
  PromotedContextRouteAudienceKindSchema,
  PromotedContextCandidateProvenanceSchema,
  PromotedContextCandidateReasonSchema,
  PromotedContextCandidateSchema,
  PromotedContextRouteReasonSchema,
  PromotedContextRouteSchema,
  PromotedContextRouteTopologySchema,
  QaContextCandidateClassSchema,
  QaContextProfileCandidateSchema,
  QaContextProfileDecisionReasonSchema,
  QaContextProfileKindSchema,
  RepositoryCommitShaSchema,
  SubtaskImplementationCheckpointIdSchema,
  SubtaskImplementationCheckpointSchema,
  buildAllowedContextSet,
  compileJitContextPacket,
  deriveContextScope,
  evaluateContextScopeAccess,
  evaluateCompiledContextByteBudget,
  evaluatePromotedContextAcceptanceRequirement,
  evaluatePromotedContextHumanConfirmationEvidence,
  evaluatePromotedContextRoute,
  evaluatePromotedContextCandidate,
  evaluateQaContextProfileCandidate,
  renderDeterministicEngineeringFact,
  SubtaskDependencySchema,
  SubtaskMaturitySchema,
  evaluateSubtaskDependencyReadiness,
  validateBudgetPolicy,
  narrowContextCandidatesForQa,
  validateSubtaskDependencies,
  validateSubtaskMaturityTransition,
  validateSubtaskTransition,
} from "../src/index.js";

describe("domain package public exports", () => {
  it("exposes the deliberate runtime contract surface", () => {
    expect(DurableTaskSchema).toBeDefined();
    expect(AuditEventSchema).toBeDefined();
    expect(ContextDigestSchema).toBeDefined();
    expect(ContextItemSchema).toBeDefined();
    expect(ContextScopeSchema).toBeDefined();
    expect(DeterministicEngineeringFactDataSchema).toBeDefined();
    expect(AcceptedPromotedContextSnapshotDataSchema).toBeDefined();
    expect(deriveContextScope).toBeTypeOf("function");
    expect(renderDeterministicEngineeringFact).toBeTypeOf("function");
    expect(buildAllowedContextSet).toBeTypeOf("function");
    expect(evaluateContextScopeAccess).toBeTypeOf("function");
    expect(PromotedContextRouteAudienceKindSchema).toBeDefined();
    expect(PromotedContextRouteSchema).toBeDefined();
    expect(PromotedContextRouteTopologySchema).toBeDefined();
    expect(PromotedContextRouteReasonSchema).toBeDefined();
    expect(evaluatePromotedContextRoute).toBeTypeOf("function");
    expect(PromotedContextCandidateSchema).toBeDefined();
    expect(PromotedContextCandidateProvenanceSchema).toBeDefined();
    expect(PromotedContextCandidateReasonSchema).toBeDefined();
    expect(evaluatePromotedContextCandidate).toBeTypeOf("function");
    expect(PromotedContextAcceptanceRequirementSchema).toBeDefined();
    expect(PromotedContextAcceptanceReasonSchema).toBeDefined();
    expect(PromotedContextAcceptanceEvaluationSchema).toBeDefined();
    expect(evaluatePromotedContextAcceptanceRequirement).toBeTypeOf("function");
    expect(PromotedContextHumanConfirmationEvidenceSchema).toBeDefined();
    expect(PromotedContextHumanConfirmationReasonSchema).toBeDefined();
    expect(PromotedContextHumanConfirmationEvaluationSchema).toBeDefined();
    expect(evaluatePromotedContextHumanConfirmationEvidence).toBeTypeOf(
      "function",
    );
    expect(QaContextProfileKindSchema).toBeDefined();
    expect(QaContextCandidateClassSchema).toBeDefined();
    expect(BoundedRetestTargetSchema).toBeDefined();
    expect(QaContextProfileCandidateSchema).toBeDefined();
    expect(QaContextProfileDecisionReasonSchema).toBeDefined();
    expect(evaluateQaContextProfileCandidate).toBeTypeOf("function");
    expect(narrowContextCandidatesForQa).toBeTypeOf("function");
    expect(JitContextPacketProfileKindSchema).toBeDefined();
    expect(JitContextPacketCompilationInputSchema).toBeDefined();
    expect(JitContextPacketSchema).toBeDefined();
    expect(JitContextPacketCompilationReasonSchema).toBeDefined();
    expect(compileJitContextPacket).toBeTypeOf("function");
    expect(SubtaskDependencySchema).toBeDefined();
    expect(SubtaskMaturitySchema).toBeDefined();
    expect(DependencyRequiredGateSchema).toBeDefined();
    expect(NativeSubagentOwnershipSchema).toBeDefined();
    expect(BudgetPolicySchema).toBeDefined();
    expect(ExecutionProviderDescriptorSchema).toBeDefined();
    expect(ChatThreadSchema).toBeDefined();
    expect(ExecutionRunSchema).toBeDefined();
    expect(ProviderThreadReferenceSchema).toBeDefined();
    expect(ProviderRunReferenceSchema).toBeDefined();
    expect(NormalizedUsageSchema).toBeDefined();
    expect(RepositoryCommitShaSchema).toBeDefined();
    expect(SubtaskImplementationCheckpointIdSchema).toBeDefined();
    expect(SubtaskImplementationCheckpointSchema).toBeDefined();
    expect(validateSubtaskDependencies).toBeTypeOf("function");
    expect(evaluateSubtaskDependencyReadiness).toBeTypeOf("function");
    expect(validateSubtaskMaturityTransition).toBeTypeOf("function");
    expect(validateSubtaskTransition).toBeTypeOf("function");
    expect(validateBudgetPolicy).toBeTypeOf("function");
    expect(evaluateCompiledContextByteBudget).toBeTypeOf("function");
    expect(domainExports).not.toHaveProperty(
      "acceptPromotedContextFromTrustedHumanAction",
    );
    expect(domainExports).not.toHaveProperty("createTrustedCapability");
    expect(domainExports).not.toHaveProperty("mintHumanCapability");
    expect(domainExports).not.toHaveProperty("acceptPromotedContext");
    expect(domainExports).not.toHaveProperty(
      "TrustedHumanPromotedContextAcceptanceResultSchema",
    );
    expect(domainExports).not.toHaveProperty(
      "TrustedHumanPromotedContextAcceptanceFailureReasonSchema",
    );
    for (const forbiddenExport of [
      "verifyByParsing",
      "isVerifiedEngineeringFact",
      "trustEngineeringFact",
      "acceptEngineeringFact",
      "approveEngineeringFact",
      "verifyDeterministicEngineeringFact",
      "probeDeterministicEngineeringFact",
      "serializeJitContextPacket",
      "measureJitContextPacketTokens",
      "pruneJitContextPacket",
      "loadAcceptedPromotedContext",
      "loadRawContextHistory",
    ]) {
      expect(domainExports).not.toHaveProperty(forbiddenExport);
    }
  });
});
